### ISSUE TITLE
[Bug] export configuration doesn't work

### ISSUE THREAD

**Issue by tmakarios** [ibbaa/keepitup#14] opened 2024-04-16 07:42 UTC
When I go into System ➡️ Export configuration and choose a place such as /storage/emulated/0/Android/data/net.ibbaa.keepitup/files/config (which was the default) and tap ✔️, it says "The specified file exists and will be overwritten" (even if the file didn't exist).  Then I tap ✔️ again and it says "An error occurred exporting the configuration", so I tap ✔️ again and the System screen is greyed out with a spinner in the middle until I do the "go back" gesture.

I'm using DivestOS 20, which is based on Android 13.

**Comment by ibbaa** [comment] 2024-04-16 19:10
Unfortunately I cannot reproduce this. On tested devices the export does work as expected and I do not experience the problems you describe.

By analyzing the relevant code I found one buggy place displaying the “catch-all-general-error” (An error occurred...) and not closing the progress spinner, so it will grey out and spin forever, which could explain one thing you experienced. But this code should never be executed in “real life” because it requires the export folder or filename to be empty which should not be possible, because the export dialog checks for that.

I suggest you reset the system settings to default values and delete everything in “/storage/emulated/0/Android/data/net.ibbaa.keepitup/files/config” folder. On opening the export dialog it should suggest the file name “keepitup_config.json” and checks for that file to exist before suggesting it and once again before writing the file using the same API, so suggesting this file name and then complaining “The specified file exists and will be overwritten” would be really weird and should not happen. Does this happen on your device?

The logs may give more insight what is happening, so if you can clearly reproduce the issue you may install the debug variant of the app, open the System settings, enable “External file logging” under “Debug settings”. Then directly reproduce the issue under “System settings” by clicking “Export configuration”. Do not play around with other things because this spams the log and makes it more difficult to find the problem. Disable “External file logging” again and go to “/storage/emulated/0/Android/data/net.ibbaa.keepitup/files/syslog” and upload the keepitup.log here on Github. There are all network tasks, host names etc. in the log so if this contains sensitive data you do not want to share, delete the tasks before.

**Comment by ibbaa** [comment] 2024-04-17 16:54
I recognized that the behaviour you describe only occurs in the release build variant, not in the debug variant. I tested DEBUG. With RELEASE I can reproduce exactly your issue. Thanks for reporting it. The bug was caused by automatic optimizations only applied on RELEASE. If you installed from F-Droid, you have RELEASE. I released 1.3.1 where this is resolved.

**Closed** 2024-04-17 16:54 UTC

**Comment by tmakarios** [comment] 2024-04-23 22:11
Thanks for fixing this!  I noticed that all the logs seem to be included in the exported configuration.  Is that intended?

**Comment by ibbaa** [comment] 2024-04-24 03:37
Yes that's by purpose
